/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as ClansIndexRouteImport } from './routes/clans/index'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfileFriendsRouteImport } from './routes/profile/friends'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProfileUserIDIndexRouteImport } from './routes/profile/$userID/index'
import { Route as ClansClanIdIndexRouteImport } from './routes/clans/$clanId/index'

const AiChatLazyRouteImport = createFileRoute('/ai-chat')()

const AiChatLazyRoute = AiChatLazyRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ai-chat.lazy').then((d) => d.Route))
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansIndexRoute = ClansIndexRouteImport.update({
  id: '/clans/',
  path: '/clans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFriendsRoute = ProfileFriendsRouteImport.update({
  id: '/profile/friends',
  path: '/profile/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIDIndexRoute = ProfileUserIDIndexRouteImport.update({
  id: '/profile/$userID/',
  path: '/profile/$userID/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansClanIdIndexRoute = ClansClanIdIndexRouteImport.update({
  id: '/clans/$clanId/',
  path: '/clans/$clanId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/ai-chat': typeof AiChatLazyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/friends': typeof ProfileFriendsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/clans/': typeof ClansIndexRoute
  '/map/': typeof MapIndexRoute
  '/clans/$clanId/': typeof ClansClanIdIndexRoute
  '/profile/$userID/': typeof ProfileUserIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/ai-chat': typeof AiChatLazyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/friends': typeof ProfileFriendsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/clans': typeof ClansIndexRoute
  '/map': typeof MapIndexRoute
  '/clans/$clanId': typeof ClansClanIdIndexRoute
  '/profile/$userID': typeof ProfileUserIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/ai-chat': typeof AiChatLazyRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/friends': typeof ProfileFriendsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/clans/': typeof ClansIndexRoute
  '/map/': typeof MapIndexRoute
  '/clans/$clanId/': typeof ClansClanIdIndexRoute
  '/profile/$userID/': typeof ProfileUserIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/ai-chat'
    | '/auth/login'
    | '/auth/register'
    | '/profile/friends'
    | '/profile/settings'
    | '/clans/'
    | '/map/'
    | '/clans/$clanId/'
    | '/profile/$userID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/ai-chat'
    | '/auth/login'
    | '/auth/register'
    | '/profile/friends'
    | '/profile/settings'
    | '/clans'
    | '/map'
    | '/clans/$clanId'
    | '/profile/$userID'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/ai-chat'
    | '/auth/login'
    | '/auth/register'
    | '/profile/friends'
    | '/profile/settings'
    | '/clans/'
    | '/map/'
    | '/clans/$clanId/'
    | '/profile/$userID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  AiChatLazyRoute: typeof AiChatLazyRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProfileFriendsRoute: typeof ProfileFriendsRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ClansIndexRoute: typeof ClansIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  ClansClanIdIndexRoute: typeof ClansClanIdIndexRoute
  ProfileUserIDIndexRoute: typeof ProfileUserIDIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans/': {
      id: '/clans/'
      path: '/clans'
      fullPath: '/clans/'
      preLoaderRoute: typeof ClansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/friends': {
      id: '/profile/friends'
      path: '/profile/friends'
      fullPath: '/profile/friends'
      preLoaderRoute: typeof ProfileFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userID/': {
      id: '/profile/$userID/'
      path: '/profile/$userID'
      fullPath: '/profile/$userID/'
      preLoaderRoute: typeof ProfileUserIDIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans/$clanId/': {
      id: '/clans/$clanId/'
      path: '/clans/$clanId'
      fullPath: '/clans/$clanId/'
      preLoaderRoute: typeof ClansClanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  AiChatLazyRoute: AiChatLazyRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProfileFriendsRoute: ProfileFriendsRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ClansIndexRoute: ClansIndexRoute,
  MapIndexRoute: MapIndexRoute,
  ClansClanIdIndexRoute: ClansClanIdIndexRoute,
  ProfileUserIDIndexRoute: ProfileUserIDIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
