/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClansRouteImport } from './routes/clans'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfileFriendsRouteImport } from './routes/profile/friends'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProfileUserIDIndexRouteImport } from './routes/profile/$userID/index'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansRoute = ClansRouteImport.update({
  id: '/clans',
  path: '/clans',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFriendsRoute = ProfileFriendsRouteImport.update({
  id: '/profile/friends',
  path: '/profile/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIDIndexRoute = ProfileUserIDIndexRouteImport.update({
  id: '/profile/$userID/',
  path: '/profile/$userID/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clans': typeof ClansRoute
  '/contact': typeof ContactRoute
  '/map': typeof MapRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/friends': typeof ProfileFriendsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/$userID/': typeof ProfileUserIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clans': typeof ClansRoute
  '/contact': typeof ContactRoute
  '/map': typeof MapRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/friends': typeof ProfileFriendsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/$userID': typeof ProfileUserIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/clans': typeof ClansRoute
  '/contact': typeof ContactRoute
  '/map': typeof MapRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/profile/friends': typeof ProfileFriendsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/$userID/': typeof ProfileUserIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clans'
    | '/contact'
    | '/map'
    | '/auth/login'
    | '/auth/register'
    | '/profile/friends'
    | '/profile/settings'
    | '/profile/'
    | '/profile/$userID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clans'
    | '/contact'
    | '/map'
    | '/auth/login'
    | '/auth/register'
    | '/profile/friends'
    | '/profile/settings'
    | '/profile'
    | '/profile/$userID'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/clans'
    | '/contact'
    | '/map'
    | '/auth/login'
    | '/auth/register'
    | '/profile/friends'
    | '/profile/settings'
    | '/profile/'
    | '/profile/$userID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClansRoute: typeof ClansRoute
  ContactRoute: typeof ContactRoute
  MapRoute: typeof MapRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ProfileFriendsRoute: typeof ProfileFriendsRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileUserIDIndexRoute: typeof ProfileUserIDIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans': {
      id: '/clans'
      path: '/clans'
      fullPath: '/clans'
      preLoaderRoute: typeof ClansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/friends': {
      id: '/profile/friends'
      path: '/profile/friends'
      fullPath: '/profile/friends'
      preLoaderRoute: typeof ProfileFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userID/': {
      id: '/profile/$userID/'
      path: '/profile/$userID'
      fullPath: '/profile/$userID/'
      preLoaderRoute: typeof ProfileUserIDIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClansRoute: ClansRoute,
  ContactRoute: ContactRoute,
  MapRoute: MapRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ProfileFriendsRoute: ProfileFriendsRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileUserIDIndexRoute: ProfileUserIDIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
