/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as ClansIndexRouteImport } from './routes/clans/index'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfileFriendsRouteImport } from './routes/profile/friends'
import { Route as DevUiPrevRouteImport } from './routes/dev/ui-prev'
import { Route as DevSpeedPrevRouteImport } from './routes/dev/speed-prev'
import { Route as DevSharedPrevRouteImport } from './routes/dev/shared-prev'
import { Route as DevNavigationPrevRouteImport } from './routes/dev/navigation-prev'
import { Route as DevMarkersPrevRouteImport } from './routes/dev/markers-prev'
import { Route as DevFriendsPrevRouteImport } from './routes/dev/friends-prev'
import { Route as DevFriendPrevRouteImport } from './routes/dev/friend-prev'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProfileUserIDIndexRouteImport } from './routes/profile/$userID/index'
import { Route as ClansClanIdIndexRouteImport } from './routes/clans/$clanId/index'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansIndexRoute = ClansIndexRouteImport.update({
  id: '/clans/',
  path: '/clans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFriendsRoute = ProfileFriendsRouteImport.update({
  id: '/profile/friends',
  path: '/profile/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiPrevRoute = DevUiPrevRouteImport.update({
  id: '/dev/ui-prev',
  path: '/dev/ui-prev',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSpeedPrevRoute = DevSpeedPrevRouteImport.update({
  id: '/dev/speed-prev',
  path: '/dev/speed-prev',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSharedPrevRoute = DevSharedPrevRouteImport.update({
  id: '/dev/shared-prev',
  path: '/dev/shared-prev',
  getParentRoute: () => rootRouteImport,
} as any)
const DevNavigationPrevRoute = DevNavigationPrevRouteImport.update({
  id: '/dev/navigation-prev',
  path: '/dev/navigation-prev',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMarkersPrevRoute = DevMarkersPrevRouteImport.update({
  id: '/dev/markers-prev',
  path: '/dev/markers-prev',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFriendsPrevRoute = DevFriendsPrevRouteImport.update({
  id: '/dev/friends-prev',
  path: '/dev/friends-prev',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFriendPrevRoute = DevFriendPrevRouteImport.update({
  id: '/dev/friend-prev',
  path: '/dev/friend-prev',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIDIndexRoute = ProfileUserIDIndexRouteImport.update({
  id: '/profile/$userID/',
  path: '/profile/$userID/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClansClanIdIndexRoute = ClansClanIdIndexRouteImport.update({
  id: '/clans/$clanId/',
  path: '/clans/$clanId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dev/friend-prev': typeof DevFriendPrevRoute
  '/dev/friends-prev': typeof DevFriendsPrevRoute
  '/dev/markers-prev': typeof DevMarkersPrevRoute
  '/dev/navigation-prev': typeof DevNavigationPrevRoute
  '/dev/shared-prev': typeof DevSharedPrevRoute
  '/dev/speed-prev': typeof DevSpeedPrevRoute
  '/dev/ui-prev': typeof DevUiPrevRoute
  '/profile/friends': typeof ProfileFriendsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/clans/': typeof ClansIndexRoute
  '/dev/': typeof DevIndexRoute
  '/map/': typeof MapIndexRoute
  '/clans/$clanId/': typeof ClansClanIdIndexRoute
  '/profile/$userID/': typeof ProfileUserIDIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dev/friend-prev': typeof DevFriendPrevRoute
  '/dev/friends-prev': typeof DevFriendsPrevRoute
  '/dev/markers-prev': typeof DevMarkersPrevRoute
  '/dev/navigation-prev': typeof DevNavigationPrevRoute
  '/dev/shared-prev': typeof DevSharedPrevRoute
  '/dev/speed-prev': typeof DevSpeedPrevRoute
  '/dev/ui-prev': typeof DevUiPrevRoute
  '/profile/friends': typeof ProfileFriendsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/clans': typeof ClansIndexRoute
  '/dev': typeof DevIndexRoute
  '/map': typeof MapIndexRoute
  '/clans/$clanId': typeof ClansClanIdIndexRoute
  '/profile/$userID': typeof ProfileUserIDIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dev/friend-prev': typeof DevFriendPrevRoute
  '/dev/friends-prev': typeof DevFriendsPrevRoute
  '/dev/markers-prev': typeof DevMarkersPrevRoute
  '/dev/navigation-prev': typeof DevNavigationPrevRoute
  '/dev/shared-prev': typeof DevSharedPrevRoute
  '/dev/speed-prev': typeof DevSpeedPrevRoute
  '/dev/ui-prev': typeof DevUiPrevRoute
  '/profile/friends': typeof ProfileFriendsRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/clans/': typeof ClansIndexRoute
  '/dev/': typeof DevIndexRoute
  '/map/': typeof MapIndexRoute
  '/clans/$clanId/': typeof ClansClanIdIndexRoute
  '/profile/$userID/': typeof ProfileUserIDIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/auth/login'
    | '/auth/register'
    | '/dev/friend-prev'
    | '/dev/friends-prev'
    | '/dev/markers-prev'
    | '/dev/navigation-prev'
    | '/dev/shared-prev'
    | '/dev/speed-prev'
    | '/dev/ui-prev'
    | '/profile/friends'
    | '/profile/settings'
    | '/clans/'
    | '/dev/'
    | '/map/'
    | '/clans/$clanId/'
    | '/profile/$userID/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/auth/login'
    | '/auth/register'
    | '/dev/friend-prev'
    | '/dev/friends-prev'
    | '/dev/markers-prev'
    | '/dev/navigation-prev'
    | '/dev/shared-prev'
    | '/dev/speed-prev'
    | '/dev/ui-prev'
    | '/profile/friends'
    | '/profile/settings'
    | '/clans'
    | '/dev'
    | '/map'
    | '/clans/$clanId'
    | '/profile/$userID'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/auth/login'
    | '/auth/register'
    | '/dev/friend-prev'
    | '/dev/friends-prev'
    | '/dev/markers-prev'
    | '/dev/navigation-prev'
    | '/dev/shared-prev'
    | '/dev/speed-prev'
    | '/dev/ui-prev'
    | '/profile/friends'
    | '/profile/settings'
    | '/clans/'
    | '/dev/'
    | '/map/'
    | '/clans/$clanId/'
    | '/profile/$userID/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DevFriendPrevRoute: typeof DevFriendPrevRoute
  DevFriendsPrevRoute: typeof DevFriendsPrevRoute
  DevMarkersPrevRoute: typeof DevMarkersPrevRoute
  DevNavigationPrevRoute: typeof DevNavigationPrevRoute
  DevSharedPrevRoute: typeof DevSharedPrevRoute
  DevSpeedPrevRoute: typeof DevSpeedPrevRoute
  DevUiPrevRoute: typeof DevUiPrevRoute
  ProfileFriendsRoute: typeof ProfileFriendsRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ClansIndexRoute: typeof ClansIndexRoute
  DevIndexRoute: typeof DevIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  ClansClanIdIndexRoute: typeof ClansClanIdIndexRoute
  ProfileUserIDIndexRoute: typeof ProfileUserIDIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans/': {
      id: '/clans/'
      path: '/clans'
      fullPath: '/clans/'
      preLoaderRoute: typeof ClansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/friends': {
      id: '/profile/friends'
      path: '/profile/friends'
      fullPath: '/profile/friends'
      preLoaderRoute: typeof ProfileFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui-prev': {
      id: '/dev/ui-prev'
      path: '/dev/ui-prev'
      fullPath: '/dev/ui-prev'
      preLoaderRoute: typeof DevUiPrevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/speed-prev': {
      id: '/dev/speed-prev'
      path: '/dev/speed-prev'
      fullPath: '/dev/speed-prev'
      preLoaderRoute: typeof DevSpeedPrevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/shared-prev': {
      id: '/dev/shared-prev'
      path: '/dev/shared-prev'
      fullPath: '/dev/shared-prev'
      preLoaderRoute: typeof DevSharedPrevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/navigation-prev': {
      id: '/dev/navigation-prev'
      path: '/dev/navigation-prev'
      fullPath: '/dev/navigation-prev'
      preLoaderRoute: typeof DevNavigationPrevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/markers-prev': {
      id: '/dev/markers-prev'
      path: '/dev/markers-prev'
      fullPath: '/dev/markers-prev'
      preLoaderRoute: typeof DevMarkersPrevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/friends-prev': {
      id: '/dev/friends-prev'
      path: '/dev/friends-prev'
      fullPath: '/dev/friends-prev'
      preLoaderRoute: typeof DevFriendsPrevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/friend-prev': {
      id: '/dev/friend-prev'
      path: '/dev/friend-prev'
      fullPath: '/dev/friend-prev'
      preLoaderRoute: typeof DevFriendPrevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userID/': {
      id: '/profile/$userID/'
      path: '/profile/$userID'
      fullPath: '/profile/$userID/'
      preLoaderRoute: typeof ProfileUserIDIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clans/$clanId/': {
      id: '/clans/$clanId/'
      path: '/clans/$clanId'
      fullPath: '/clans/$clanId/'
      preLoaderRoute: typeof ClansClanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DevFriendPrevRoute: DevFriendPrevRoute,
  DevFriendsPrevRoute: DevFriendsPrevRoute,
  DevMarkersPrevRoute: DevMarkersPrevRoute,
  DevNavigationPrevRoute: DevNavigationPrevRoute,
  DevSharedPrevRoute: DevSharedPrevRoute,
  DevSpeedPrevRoute: DevSpeedPrevRoute,
  DevUiPrevRoute: DevUiPrevRoute,
  ProfileFriendsRoute: ProfileFriendsRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ClansIndexRoute: ClansIndexRoute,
  DevIndexRoute: DevIndexRoute,
  MapIndexRoute: MapIndexRoute,
  ClansClanIdIndexRoute: ClansClanIdIndexRoute,
  ProfileUserIDIndexRoute: ProfileUserIDIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
