name: Deploy VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 204.168.158.148
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            bash -l -c "
            echo CONNECTED
            cd /root/project/GPS_APP_SzKM
            git pull origin main
            docker compose down
            docker compose up -d --build
            echo DEPLOY DONE
            "